### ISSUE TITLE
Namensfindung

### ISSUE THREAD

**Issue by iblech** [curry-club-aux/curry-club-augsburg.de#1]
Ich sammle hier mal die bisher eingegangenen Vorschläge:
1. Augsburger Haskell-Stammtisch
2. Augsburger funktionaler Stammtisch
3. Augsburger Curry-Club
4. Haskellistas & Lambdroiden Augsburg

Vorschlag 1 finde ich weniger geeignet, da er andere Sprachen ausschließt. Vorschlag 3 finde ich sehr gut, da _Curry_ ein Name ist, mit dem sich sicherlich die Anhänger aller funktionalen Sprachen identifizieren können. Es gibt allerdings auch schon eine [Sprache mit diesem Namen](http://www-ps.informatik.uni-kiel.de/currywiki/start) und irgendwie ist mir der Name zu wenig "fancy".

Momentan gefällt mir daher Vorschlag 4 am besten. Kann man ihn noch verkürzen? Oder eine andere Konstruktion mit "lambda" im Namen suchen? Weitere Ideen (teilweise lächerlich):

a. Augsburger monadischer Stammtisch
b. Augsburger polymorpher Stammtisch
c. Functionallies
d. Augsburger Lambdawürfel (in Anspielung auf den lambda cube)
e. Polymorphe Haskellistas Augsburg

**Comment by iblech** [comment]
Man kann auch zwischen der Bezeichnung der Personen und der Bezeichnung des Treffens unterscheiden. Zum Beispiel: "Augsburgs Haskellistas & Lambdroiden laden ein zum monadischen Stammtisch."

**Comment by Profpatsch** [comment]
Ich bin natürlich für Vorschlag 4, da meine Idee. :)

polymorph finde ich nicht so gut, da es sehr von OO belastet ist.
„Monade“ im Namen ist eher abschreckend für die meisten, denke ich.

„monadischer Stammtisch“ klingt fast wie „monatlicher Stammtisch“, da lässt sich doch bestimmt was machen: „monadlicher Stammtisch“ :D

Yay, schlechte Wortspiele.

**Comment by iblech** [comment]
"Monadlich" hat den weiteren Vorteil, dass es sehr süß klingt!

![warm fuzzy](https://wiki.haskell.org/wikiupload/4/47/Haskell_nuclear_xyzzy.png)
![warm fuzzy](https://wiki.haskell.org/wikiupload/1/1d/Monica_monad_falconnl.png)

**Comment by iblech** [comment]
"Monadlich" hat den weiteren Vorteil, dass es sehr süß klingt!

![warm fuzzy](https://wiki.haskell.org/wikiupload/4/47/Haskell_nuclear_xyzzy.png)
![warm fuzzy](https://wiki.haskell.org/wikiupload/1/1d/Monica_monad_falconnl.png)

**Comment by sternenseemann** [comment]
Vorschlag 4 Finde ich recht fancy, sonst 1 und 2.

**Comment by timjb** [comment]
"monadlicher Stammtisch" ist nett. Das können wir für die Webseite verwenden (wenn wir uns für diesen Rhythmus entscheiden). Ich finde die Vorschläge 3, 4 und 1 gut (absteigend in dieser Reihenfolge).

Zwei weitere schlechte Vorschläge:

f. Augsburger kartesisch abgeschlossener Stammtisch
g. Augsburg [Church](http://de.wikipedia.org/wiki/Alonzo_Church) of Lambda

**Comment by sternenseemann** [comment]
@timjb's Präferenz kann ich zustimmen, wobei ich mich nicht zwischen 3 u. 4 entscheiden kann.

"Monadlicher Stammtisch" könnte man auf der Website verwenden, wie z. B. "Komm zu unserem monadlichen Stammtisch" in einer Überschrift. Taugt aber IMO nicht als Gruppen Titel, weil zu festlegend usw.

**Comment by iblech** [comment]
"Haskellistas und Lambdroiden aufgepasst! Der Augsburger Curry-Club
lädt zum monadlichen Stammtisch ein." (Ich denke nur laut.)

**Comment by sternenseemann** [comment]
Klingt gut. (Btw, ich frage mal $Leute wg. ML-Infrastruktur)

**Comment by Profpatsch** [comment]
Mit Curry-Club kann ich leben, das geht ins Ohr.

Chaos Curry Club? :D

ist die Frage, wie gut sich Leute was drunter vorstellen können, wenn sie nur Curry-Club hören. Dann muss das 'y' schon als blaues umgedrehtes Lambda dargestellt werden. :)

**Comment by timjb** [comment]
Oder so:

![curry-club-aux](https://cloud.githubusercontent.com/assets/124073/6714047/8347d876-cd96-11e4-83e2-e50e6d1ea343.png)

"Cartesian Closed Chaos Curry Club"

**Comment by sternenseemann** [comment]
ow, hübsch

**Comment by Profpatsch** [comment]
Haha, sehr cool. +1

**Comment by iblech** [comment]
jup, super! +1

**Comment by sternenseemann** [comment]
Das heißt wir einigen uns auf?

**Comment by fthomas** [comment]
Als interessierter Beobachter finde ich den Augsburger Curry-Club super.

**Comment by iblech** [comment]
@lukasepple Glaube schon, ja!

@fthomas Owner-Einladung ist verschickt. Willkommen!

**Comment by iblech** [comment]
Moritz meinte gerade auf openlab-alle: "Ich bin für Curry-Club. :)"

**Comment by sternenseemann** [comment]
Ich glaube das ist jetzt entschieden, oder?

**Comment by iblech** [comment]
Jup, denke schon. :-) Ich hatte deinen vorherigen Kommentar als "Das heißt wir einigen uns darauf?" missgelesen. Ich schließe jetzt mal.

**Comment by iblech** [comment]
@timjb++  # hat den favorisierten Vorschlag gemacht und gezeigt, wie man mit Adjektiven seine Fancyness hochschrauben kann

**Comment by fthomas** [comment]
@iblech Die Einladung nehme ich dankend an. :-)

**Comment by timjb** [comment]
Achtung! Ich werde jetzt gleich die Github-Organisation umbenennen zu `curry-club-aux`. Ich weiß nicht, ob Github Redirects beim Umbenennen einrichtet. Es kann also gut sein, dass ihr lokal eure git remotes anpassen müsst.

**Comment by rueger** [comment]
Hi, ich finde eure Initiative total super! Augsburg könnte man auch agb abkürzen (so wie die internationale Airport Bezeichnung, https://de.wikipedia.org/wiki/Flughafen_Augsburg).
Persönlich finde ich sprechende Namen besser - auch wenn der Domainname etwas länger wird.
BTW: Tolles Logo!

**Comment by pRiVi** [comment]
Ich bitte auch um eine Einladung. :-)

**Comment by timjb** [comment]
@pRiVi Herzlich willkommen!
