### ISSUE TITLE
Gestaltung der Website, Logo, besseren CSS

### ISSUE THREAD

**Issue by sternenseemann** [curry-club-aux/curry-club-augsburg.de#10]

**Comment by timjb** [comment]
Siehe auch #17.

**Comment by timjb** [comment]
#17 wurde gemerged.

**Comment by Profpatsch** [comment]
@timjb Vllt. sollten wir auch anfangen, bei solchen größeren Projekten sich im Voraus einen Issue zu assignen (und am besten einen Kommentar hinterlassen), dann kann man sich doppelte Arbeit sparen.

**Comment by timjb** [comment]
Ja, das wäre sinnvoll.
