### ISSUE TITLE
Abstimmung Tag/Turnus

### ISSUE THREAD

**Issue by sternenseemann** [curry-club-aux/curry-club-augsburg.de#11]
Wir brauchen dringend eine ML.

> lasst uns mal etwas entscheiden:
> 
> (a) Turnus des Curry Clubs: https://dudle.inf.tu-dresden.de/Curry_Club_Turnus/
> (b) Wochentag: https://dudle.inf.tu-dresden.de/ew3c4t3z/

**Comment by maxhbr** [comment]
Gibt es schon konkrete Vorschläge für einen ersten Termin?

**Comment by sternenseemann** [comment]
nee, lasst mich mal aus .gr zurückkommen :)

**Comment by iblech** [comment]
Nachdem .gr, der LIT und der Perl-Stammtisch jetzt erledigt sind, lasst uns langsam die Planung konkretisieren! Wir sollten mit der Auswertung der Wochentagsumfrage aber noch auf @makarius warten, und allgemein bedenken: Manche von uns, zum Beispiel @maximilianhuber und @MatthiasHu, sind am Wochenende nicht in Augsburg und müssten daher extra reinfahren. Insofern wäre ein Termin unter der Woche doch besser. Vielleicht könnte man, wenn man die Treffen nicht zu spät am Abend beginnt, dadurch entstehende Nachteile für Leute, die sich gelegentlich auf Exen fieser Lehrer vorbereiten müssen :-), begrenzen?

**Comment by iblech** [comment]
Und erinnert sich jemand an den Grund, wieso nicht Di bis Do in der Umfrage auswählbar waren? OpenLab-Besetzung durch andere Gruppen vielleicht?

**Comment by makarius** [comment]
OK, ich habe nun Mo und Fr angetickt.  Di und Mi ginge auch, stand hier aber nicht zur Auswahl.

**Comment by sternenseemann** [comment]
Di, Mi und Do sind schon durch 3d-Druck, offener Abend und Chaos/Plenum belegt.

Abend ist okay, solange Samstag/Freitag.

**Comment by iblech** [comment]
@lukasepple und @Profpatsch, wie sieht es bei euch denn montags aus? Da habt ihr Fragezeichen eingetragen. Gäbe es ein Zeitfenster, das euch passt? :-)

**Comment by sternenseemann** [comment]
Eher nicht.

**Comment by Profpatsch** [comment]
Nein, Montag ist jetzt fest belegt von einem anderen wöchentlichen Termin. Ich passe das mal an.

**Comment by maxhbr** [comment]
Wie oft ist das Plenum denn? Da es ja scheinbar der Monatliche Turnus wird, könnte man ja immer die Termine wählen, an denen der Donnerstag frei ist.

Zu einem Termin am Wochenende: Ich (und scheinbar auch @MatthiasHu) habe(n) am Wochenende eine recht lange Anfahrt. Auch kann man an den entsprechenden Wochenenden dann nichts längeres unternehmen.

Schade, dass Montag inzwischen belegt ist. Welche Veranstaltung hat uns denn den Termin denn bekommen?

**Comment by Profpatsch** [comment]
@maximilianhuber Nein, nur bei mir persönlich.

**Comment by sternenseemann** [comment]
Donnerstag ist auch sehr oft, wie erähnt, c3a zu gange.

**Comment by Profpatsch** [comment]
Donnerstag ist (eigentlich) immer abwechselnd Plenum und c3a, in letzter Zeit aber unregelmäßig. Vllt. macht es Sinn, das Plenum nur einmal im Monat anzusetzen, dann gäbe es da noch einen Termin.

**Comment by Profpatsch** [comment]
Ich preferiere halt Samstag, weil man da normalerweise keine festen Termine hat, und dann zumindest 50–75% der Termine wahrnehmen kann. Aber ich sehe den Punkt mit der weiten Anreise.

**Comment by Profpatsch** [comment]
So, jetzt noch einmal ein Doodle mit den zwei gleichaufliegenden Terminen und dem Donnerstag, den wir in Absprache noch dazugewinnen konnten.

https://dudle.inf.tu-dresden.de/hsd3psqg/

**Comment by Profpatsch** [comment]
Es sieht so aus, als wäre es jetzt der Donnerstag geworden. Sind wir uns da einig?

**Comment by maxhbr** [comment]
Sieht so aus, ja. Aber im vergleich zur ersten Abstimmung fehlen noch @pRiVi, @richi235, @fthomas und @waaaaargh (ich hoffe ich habe die namen im dudle den gihub-accounts richtig zugeordnet)

**Comment by iblech** [comment]
Und das Fragezeichen bei @lukasepple macht mir Sorgen!

**Comment by sternenseemann** [comment]
Unter der Woche ist halt bei Schülern immer beschissen :(

**Comment by Profpatsch** [comment]
@maximilianhuber Ich habe auf der ML geschrieben, dass nur diejenigen abstimmen sollen, die vorhaben regelmäßig zu kommen.

@lukasepple Stell dich nicht so an, Schüler haben es auch nicht schwerer als Erwachsene, die den ganzen Tag arbeiten …
Im Notfall holt dich halt einer ab. Und wir starten einfach früh genug. Es war eh ~19:00 geplant.

À prospos Uhrzeit, ich hab da mal noch ein Dudle gemacht:
https://dudle.inf.tu-dresden.de/Uhrzeit_Curry_Club/

**Comment by sternenseemann** [comment]
@Profpatsch Ja, ich muss das dann bloß meinen Eltern als das Wichtigste meines Lebens verkaufen

**Comment by iblech** [comment]
@Profpatsch: Kannst du noch 17:00 Uhr und 17:30 Uhr ergänzen, für den Fall, dass das für @lukasepple besser ist?

**Comment by iblech** [comment]
@lukasepple: Wenn es hilft, kann ich auch immer in meiner "Autorität" als wissenschaftlicher Mitarbeiter am Mathe-Institut was schreiben (gerne auch an Schulen).

**Comment by sternenseemann** [comment]
Nee, bin erst um 16:39 daheim an dem Tag…

**Comment by Profpatsch** [comment]
Dann würde ich 19:00 Uhr vorschlagen, Donnerstags.

Wollen wir lieber einen vierwöchentlichen oder einen monatlichen Turnus? Chaostreff ist zweiwöchentlich, also wäre ersteres einfacher. Zur Not dann halt immer nte Woche des Monats, außer es ist Chaostreff, dann eine Woche später …

**Comment by iblech** [comment]
@lukasepple Ist 19:00 Uhr auch deine Lieblingszeit? Du hast ja bei 19:30 Uhr Fragezeichen angegeben. Wir sollten uns, wenn wir uns jetzt schon unter der Woche treffen, zumindest in der Uhrzeit nach dir richten! Und den anderen passt ja jede Zeit ab 18:00 Uhr.

**Comment by iblech** [comment]
@Profpatsch Grundsätzlich, wenn es keine Nebenbedingungen gäbe, fände ich monatlich besser (einfacher zum merken). Ist mir aber eigentlich auch völlig egal.

**Comment by Profpatsch** [comment]
Dann würde ich sagen trotzen wir der arbiträren Monatseinteilung des Kalenders, gehen den Weg des geringsten Widerstands und machen es ab 7. Mai 2015 vierwöchentlich um 19:00 Uhr.

Letzte Einwände?

**Comment by iblech** [comment]
Vorher geht nicht, oder?

Ich habe nur den Meta-Einwand, noch auf die Uhrzeit-Meinung von @lukasepple zu warten.

**Comment by Profpatsch** [comment]
Alternativ ist auch der 23. möglich. Aber das ist ja in <1 Woche.

**Comment by maxhbr** [comment]
wir hätten dann halt noch keinen großen Vortag bzw. kein Thema. Aber um sich mal zu treffen wäre der frühe Termin doch nicht schlecht, oder?

**Comment by iblech** [comment]
Ich könnte durchaus einen Vortrag halten (Parsing mit Parsec, Kategorientheorie, Homotopietyptheorie). Außerdem bin ich davon überzeugt, dass @timjb zum Beispiel Lenses und seine Rubik-Bibliothek vorstellen kann!

**Comment by waaaaargh** [comment]
Aus rein eigennützigen Gründen wäre ich für einen Parsec-Vortrag :+1:

**Comment by maxhbr** [comment]
Parsec würde mich auch interessieren.

Würde auch 5-10min etwas über mein aktuelles kleines Projekt erzählen.

(Wir könnten das hier mit https://github.com/curry-club-aux/curry-club-augsburg.de/issues/13 zusammenführen)

**Comment by Profpatsch** [comment]
Also erstes Treffen nächste Woche, der 23.4.2015, dann vierwöchentlich, um 19:00 Uhr.
