### ISSUE TITLE
Vorschläge für / Planung des ersten Treffens

### ISSUE THREAD

**Issue by maxhbr** [curry-club-aux/curry-club-augsburg.de#13]
Ich würde hier gerne einen Platz schaffen, um das erste Treffen zu planen und die ersten Vorträge/Themen zu fixieren.

Ich würde gerne über mein Projekt [mySortMaildir](https://github.com/maximilianhuber/mySortMaildir) berichten.

Meiner Meinung nach sollten wir uns beim ersten Treffen nicht darauf konzentrieren einführenden Vorträge/Themen für Außenstehende zu haben (außer es gibt hier jemanden der das gerne hätte), da das erste Ziel ist, sich mal kennen zu lernen.

**Comment by iblech** [comment]
Hier kurze Erinnerung, dass vor unserem ersten Treffen am morgigen Montag der Perl-Stammtisch stattfindet: über [Pugs, die experimentelle Haskell-Implementierung von Perl 6](http://augsburg.pm.org/). 19:00 Uhr im OpenLab.

**Comment by iblech** [comment]
Ah, und noch inhaltlich zu unseren Treffen: Neben klassischen Vorträgen eignen sich möglicherweise auch Code-Durchsichten (bzw. Live-Code-Neuprogrammierungen). Ich bin beispielsweise an dem [Rubik-Würfel-Code](https://github.com/timjb/diagrams-rubiks-cube) von @timjb interessiert.

**Comment by timjb** [comment]
@iblech Huch, wir treffen uns schon morgen?!? Wo und wann wurde das denn vereinbart? Ich dachte, es stünde noch kein Termin fest (siehe #11).

**Comment by iblech** [comment]
Sorry für die Verwirrung! Nein, der Perl-Stammtisch trifft sich morgen.
Wir, der Curry Club, müssen noch einen Termin überlegen.

**Comment by timjb** [comment]
Da habe ich wohl falsch geklammert.

**Comment by iblech** [comment]
Hier ein Vorschlag für ein erstes Thema (zusätzlich zur Projektvorstellung von @maximilianhuber): _Monadische Parserkombinatoren._

Wir könnten:
1. Sehen, wie einfach man eine eigene naive Kombinatorbibliothek implementieren kann.
2. Diskutieren, was eine naive Bibliothek bereits leistet, aber auch, was zu "industrial-strength" noch fehlt.

Danach wird jeder zum Beispiel Parsec einsetzen können, um eigene Parser zusammenzustellen. Bei Interesse könnte man später das Thema vertiefen und über die Neuerungen seit Parsec sprechen.

Das Thema eignet sich auch insofern, als dass es überhaupt nicht Haskell-spezifisch ist. Monadische Parserkombinatoren sind in allen Sprachen sinnvoll (ob man nun do-Notation verwenden möchte oder nicht).

**Comment by timjb** [comment]
Ich kann einen Kurz-Vortrag über [typsicheres Routing in Spock](http://www.spock.li/2015/04/19/type-safe_routing.html) halten. Es würde sich auch lohnen, gemeinsam die Implementierung durchzulesen.

Ich würde auch gerne über Lenses reden, aber dafür brauch ich mehr als eine Woche Vorbereitungszeit.
