### ISSUE TITLE
Flyer / Werbematerialien

### ISSUE THREAD

**Issue by maxhbr** [curry-club-aux/curry-club-augsburg.de#14]
Wollen wir sowas wie Flyer um für den Curry-Club Werbung zu machen?
Wollen wir überhaupt, dass sich das hier schnell vergrößert?

An der Uni fängt bald eine Vorlesung 'Formale Methoden' an, wo sich theoretisch überdurchschnittlich viele funktionale Programmierer treffen und dort gäbe es möglicherweise Interessenten.

**Comment by iblech** [comment]
On Wed, Mar 25, 2015 at 03:02:49AM -0700, Maximilian Huber wrote:

> Wollen wir sowas wie Flyer um für den Curry-Club Werbung zu machen?

Fände ich gut!

> Wollen wir überhaupt, dass sich das hier schnell vergrößert?

Das ist mir nicht an sich wichtig. Wichtig ist mir nur, dass zum einen wir coolen Nerdtalk machen können und zum anderen dass jeder, der sich für einen funktionalen Sprachenstammtisch interessiert, auch Bescheid weiß, dass es einen solchen in Augsburg gibt. :-)

**Comment by larsrh** [comment]
Sticker existieren mittlerweile. Danke @timjb!
