### ISSUE TITLE
Mailingliste

### ISSUE THREAD

**Issue by iblech** [curry-club-aux/curry-club-augsburg.de#15]
@lukasepple, gibt es da von $Leuten schon Neuigkeiten?

**Comment by sternenseemann** [comment]
Ich forsche da mal weiter. Bis jetzt noch nicht wirklich was.

**Comment by Profpatsch** [comment]
Ich habe gerade erst gemerkt, dass hier Gespräche laufen. oO

Ich pinge mal weiter die Leute an, v.A. den @waaaaargh

**Comment by Profpatsch** [comment]
Sollte durch #16 gelöst werden.
