### ISSUE TITLE
Einrichtung einer Mailingliste

### ISSUE THREAD

**Issue by waaaaargh** [curry-club-aux/curry-club-augsburg.de#16]
Der @Profpatsch hat mich darauf angesprochen, dass der CurryClub eine Mailingliste braucht. Mache ich gerne, dazu brauche ich aber den @timjb, weil der zur Zeit Inhaber der Domain `curry-club-augsburg.de` ist.

Ich brauche folgende DNS-Records:
- `curry-club-augsburg.de IN MX 5.135.127.50`
- `lists.curry-club-augsburg.de IN A 5.135.127.50`
- `lists.curry-club-augsburg.de IN MX 5.135.127.50`

Bitte habt Verständnis dafür, dass ich gerade dabei bin, auch die Mail-Infrastruktur des OpenLab umzuziehen, daher wird es ein paar Tage dauern, biss die Liste funktioniert.

Wen darf ich denn als List-Owner eintragen?

**Comment by timjb** [comment]
Die DNS-Records sind gesetzt. Du darfst mich (tim@timbaumann.info) als List-Owner eintragen.

**Comment by timjb** [comment]
Wir haben jetzt eine Mailingliste: [http://lists.curry-club-augsburg.de/listinfo/curry-talk](http://lists.curry-club-augsburg.de/listinfo/curry-talk)

Danke an @waaaaargh :+1:

**Comment by waaaaargh** [comment]
Ah, halt, die funktioniert noch nicht.

**Comment by Profpatsch** [comment]
Wie ist die ETA?

**Comment by waaaaargh** [comment]
Schaut relativ freundlich aus, Mailman empfängt und sendet jetzt Mails. Da ich das wie gesagt in einem Aufwasch mit der gesamten E-Mail-Infrastruktur des OpenLab und des c3a mache (#YOLO) wird es noch mindestens bis Sonntag Abend dauern.

**Comment by waaaaargh** [comment]
So, Mailinigliste läuft: http://lists.curry-club-augsburg.de/listinfo/curry-talk

**Comment by maxhbr** [comment]
Kann ich mich in die Mailingliste auch eintragen, ohne dass ich Mails erhalte, bzw. kann man einer Adresse, die nicht in der Liste ist, erlauben Mails an die Liste zu schreiben?

Situation:
Ich schreibe von Adresse A, lasse mir Mailinglisten aber an Adresse B schicken, von wo aus die dann nach A sortiert werden.
Jetzt kann ich von A aus aber keine Mail an die Mailinglistes schicken, da nur B diese aboniert hat.

**Comment by waaaaargh** [comment]
@maximilianhuber Das müsste gehen. Als list-owner hat @timjb die Option, auch Posts von Nichtmitgliedern zuzulassen.

**Comment by timjb** [comment]
Anscheinend bekomme ich als Owner immer eine Mail, wenn ein Nicht-Listen-Mitglied an die Liste schreibt, und kann die Nachricht zulassen. Ich habe dann auch die Möglichkeit, Nachrichten von dem Absender immer zuzulassen. Für @maximilianhuber ist das schon geschehen.

**Comment by maxhbr** [comment]
Danke
