### ISSUE TITLE
Twitter-Account?

### ISSUE THREAD

**Issue by timjb** [curry-club-aux/curry-club-augsburg.de#19]
Ich bin dafür, einen Twitter-Account für Announcements einzurichten. Will das jemand übernehmen?

**Comment by iblech** [comment]
Finde ich gut! (Bin aber nicht auf Twitter.)

**Comment by sternenseemann** [comment]
Kann ich nächste Woche machen, wenn sich niemand findet

**Comment by Profpatsch** [comment]
Beehive-Bridge aufbauen. Wo soll beehive laufen? Ich schlage eine VM auf dem Server des OLAs vor.

**Comment by sternenseemann** [comment]
Brauchen wir das wirklich?

**Comment by Profpatsch** [comment]
Hm, bin nicht sicher. Aber kann nicht schaden, wenn das automatisch befüllt wird.

**Comment by timjb** [comment]
Wir haben jetzt einen Account: [@curry_club_aux](https://twitter.com/curry_club_aux)

Ich, @Profpatsch, @lukasepple und @larsrh sind Admins.

**Comment by sternenseemann** [comment]
:+1:

**Comment by Profpatsch** [comment]
Cool! Macht Sinn, glaub ich. Und sehr cooles Banner. :P
