### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by sternenseemann** [curry-club-aux/curry-club-augsburg.de#2]
Was sollen wir da tuen? Depended auf #1.

**Comment by timjb** [comment]
Vorschlag 1: Die offensichtliche Option:

![haskell-aux](https://cloud.githubusercontent.com/assets/124073/6713437/8e03c710-cd92-11e4-9c46-2815e3ae3944.png)

Wenn man betonen möchte, dass andere funktionale Programmiersprachen auch willkommen sind, dann könnte man auch überlegen, nur dem Lambda eine Farbe zu geben, die einen starken Kontrast zum Hintergrund aufweist und den Rest des Haskell-Logos nur mit einem Farbton Unterschied zum Hintergrund einzufärben.

**Comment by sternenseemann** [comment]
Vorschlag klingt gut.

**Comment by timjb** [comment]
Vorschlag 2: Irgendwas mit dem Stadtwappen anstellen. (Ich finde das Logo vom [Perl-Stammtisch](http://augsburgpm.github.io/) super!)

**Comment by timjb** [comment]
Wir könnten auch das Haskell-Logo mit "Augsburg" (oder "Aux") Schriftzug auf den Flipdots zeichnen, das ganze abfotografieren und das Bild als Logo benutzen.

**Comment by sternenseemann** [comment]
@timjb Hast du das Curry-Club-Logo aus dem Namensthread noch ohne Rahmen und in benutzbar? Dann bau' ich das in die Website ein.

**Comment by timjb** [comment]
Ich habe das Logo noch [als SVG](https://dl.dropboxusercontent.com/u/1554469/curry-club-helvetica-neue.svg). Bitte noch nicht benutzen! Ich bin gerade noch auf der Suche nach Schriftarten, die erstens besser aussehen als die Helvetica Neue und in denen zweitens das umgedrehte Lambda etwas weniger wie ein Fremdkörper wirkt.

**Comment by timjb** [comment]
Kennt jemand eine geometrische Groteske mit großer Unterlänge?

**Comment by iblech** [comment]
Nicht unbedingt ein Logo, wollte es aber trotzdem posten: Aus dem [ersten Pizzaseminar](http://pizzaseminar.speicherleck.de/index-1.html).

![](http://pizzaseminar.speicherleck.de/lambda-klein.png)

**Comment by timjb** [comment]
So, ich habe ein paar Varianten erstellt.

Der originale Vorschlag, gepostet in #1 (Helvetica Neue):

![curry-club-helvetica-neue](https://cloud.githubusercontent.com/assets/124073/6722378/1949051a-cdd9-11e4-99fb-6cac5cb5069b.png)

Fira Sans:

![curry-club-fira-sans](https://cloud.githubusercontent.com/assets/124073/6722383/28b8e60a-cdd9-11e4-9378-e8554cd9550a.png)

Futura:

![curry-club-futura](https://cloud.githubusercontent.com/assets/124073/6722385/349f8bd6-cdd9-11e4-9642-46bd55b19d66.png)

Avenir:

![curry-club-avenir](https://cloud.githubusercontent.com/assets/124073/6722390/425e246c-cdd9-11e4-88c7-cb27227da834.png)

Fira Sans, rot-grün:

![curry-club-fira-sans-rot-gruen](https://cloud.githubusercontent.com/assets/124073/6722440/ba480cb8-cdd9-11e4-9d5c-78940023f77d.png)

Fira Sans, grün-rot:

![curry-club-fira-sans-gruen-rot](https://cloud.githubusercontent.com/assets/124073/6722414/7e35d75a-cdd9-11e4-9b2c-05cbf6f76087.png)

Avenir, grün-rot:

![curry-club-avenir-gruen-rot](https://cloud.githubusercontent.com/assets/124073/6722406/6b510a6a-cdd9-11e4-8052-6146796ffcc1.png)

Warum grün und rot? Erstens, weil ich finde, dass der Schriftzug mit diesen warmen Farben einladender wirkt. Zweitens, weil es Farben aus dem Stadtwappen sind. Drittens, weil die klassischen Currypasten in der thailändischen Küche auch grün und rot sind.

Natürlich sind auch die Futura oder die Helvetica Neue in grün-rot oder rot-grün denkbar, ich habe aber die Varianten noch nicht erstellt.

Discuss!

**Comment by iblech** [comment]
Hier habe ich keine starke Meinung. Nehmt also keine Rücksicht auf mich!

Ich finde rot als Hauptfarbe besser als grün. Bei dem roten Logo bin ich mir aber nicht ganz sicher, ob das gelb so gut passt. Ich finde auch die Farbgebung von http://www.haskell.org/ sehr schön.

Zur Schrift: Finde den Schnörkel beim "g" von Fira Sans nicht ganz so gut. Die restlichen Schriftarten finde ich gleich gut.

**Comment by timjb** [comment]
Ein paar weitere Farbkombinationen (mit Schrift Futura):

![curry-club-futura-haskellorg](https://cloud.githubusercontent.com/assets/124073/6727191/f0edd950-ce1f-11e4-9b49-7bc42e60a398.png)

![curry-club-futura-hintergrund-dunkelrot](https://cloud.githubusercontent.com/assets/124073/6727194/f6d09498-ce1f-11e4-9fe7-42d0b01863b3.png)

![curry-club-futura-hintergrund-grau](https://cloud.githubusercontent.com/assets/124073/6727197/fc9a830c-ce1f-11e4-97cc-f292bc1fa092.png)

![curry-club-futura-rot-rot](https://cloud.githubusercontent.com/assets/124073/6727199/027b5238-ce20-11e4-99c5-7f1a997b1230.png)

![curry-club-futura-gruen-gruen](https://cloud.githubusercontent.com/assets/124073/6727188/eadc73b4-ce1f-11e4-92ad-d10c0c26601d.png)

**Comment by iblech** [comment]
Das sind sehr schöne neue Vorschläge! Meine persönliche Rangfolge: 1|2|4 > 5 > 3.

**Comment by bene1618** [comment]
Hi, ich finde ebenfalls rot als Hauptfarbe schöner. Es gibt allerdings drei Punkte, die mich an allen Vorschlägen stören (wahrscheinlich alles Geschmackssache).
1. Ich finde es störend, dass das grüne y (umgedrehte λ, ich weiß...) so einen großen Abstand zum r hat.
2. Es gibt in jeder Schriftart die Zeichen y und =, also könnte man das umgedrehte Haskell-Logo einfach in der Schriftart nachbauen. Das gäbe ein konsistenteres Gesamtbild.
3. Avenir und Fira Sans sind kommerzielle Schriftarten.

Daher wäre mein Vorschlag folgender (die Schrift ist URW Gothic Book, zu der ich leider die Lizenz auf die Schnelle nicht gefunden habe; ich glaube aber, es ist GPL):
![curry_club](https://cloud.githubusercontent.com/assets/7225071/6727359/9dce1f30-ce21-11e4-959b-a83539fe4974.png)

Der XeLaTeX-Quellcode dafür ist:

``` tex
\documentclass{standalone}

\usepackage{fontspec}
\usepackage{tikz}

\setmainfont{URW Gothic Book}

\begin{document}
\begin{tikzpicture}[every node/.style={anchor=base west}]
  \node[color=green!20] at (0,0) {\bf\phantom{Curr}\kern -0.17em y\kern -0.25em \raisebox{-0.5ex}{=}};
  \node[color=white] at (0,0) {\bf\phantom{Curr}\kern -0.03em y};
  \fill[color=white] (0.93,0.05) -- (0.98,0.2) -- (0.88,0.2);
  \node[color=white] at (0,0) {\bf\phantom{Curr}\kern +0.03em y};
  \node[color=green!40!black] at (0,0) {\bf\phantom{Curr}y};
  \node[color=red!50!black] at (0,0) {\bf Curr\phantom{y} Club Augsburg};
\end{tikzpicture}
\end{document}
```

**Comment by timjb** [comment]
@benevs Ich stimme dir zu, dass der Abstand zwischen "r" und "y" unschön ist. Ich finde aber, das Haskell-Logo sollte immer noch deutlich als das Haskell-Logo erkennbar sein.  Mein Vorschlag, um dieses Problem zu lösen, ist, ein kleines Stück oben aus dem ">" vor dem "y" wegzuschneiden.

Drei Varianten dieser Idee, mit der freien Schriftart "Ubuntu":

![curry-club-ubuntu-rot-rot-abgeschnitten1](https://cloud.githubusercontent.com/assets/124073/6728533/c67e7a0c-ce2a-11e4-8999-6052e25f7cb1.png)

![curry-club-ubuntu-rot-rot-abgeschnitten2](https://cloud.githubusercontent.com/assets/124073/6728540/ccd07a4a-ce2a-11e4-9e8a-e4da0f2b016d.png)

![curry-club-ubuntu-rot-rot-abgeschnitten3](https://cloud.githubusercontent.com/assets/124073/6728740/5b4a1e1a-ce2c-11e4-829d-f2fbd50af3c3.png)

Soweit ich weiß, ist es erlaubt, Schriftarten, für die man mit Kauf des Betriebssystems (also bei mir MacOS) eine Nutzungslizenz erworben hat, zum Erstellen von Logos oder ähnlichem zu verwenden. Was z.B. nicht erlaubt ist, ist die Fontdatei selbst weiterzuverbreiten, oder sie in eine Webseite oder PDF-Datei einzubinden.

**Comment by iblech** [comment]
Die Ubuntu-Schriftart finde ich schön und, aufgrund ihres freien Hintergrunds, auch sehr unterstützenswert! Beim Mathezirkel haben wir zur Schleichwerbung auch immer die Ubuntu-Schriftart für Flyer und Plakate verwendet.

**Comment by fthomas** [comment]
:+1: für die dritte Variante mit dem abgeborchenen >. Die Schriftart finde ich auch sehr hübsch.

**Comment by bene1618** [comment]
Die dritte Variante finde ich auch sehr hübsch.

**Comment by timjb** [comment]
Angelehnt an das Logo vom OpenLab:

![curry-club-kapital](https://cloud.githubusercontent.com/assets/124073/6733435/82cb639c-ce52-11e4-9f94-70bf8ed32294.png)

![currying-club-kapital](https://cloud.githubusercontent.com/assets/124073/6733437/84f02f18-ce52-11e4-8bf1-48c613a53c6a.png)

Edit 1: Dafür gesorgt, dass "Augsburg" nicht mehr oben absteht

Edit 2: Kerning in "Club" verbessert

**Comment by iblech** [comment]
Finde ich sehr schön! Die erste Variante gefällt mir besser. Da schneidet das "=" schön das Wort ab. Übrigens ist "Curry Club Augsburg" auch etwas einfacher auszusprechen als "Currying Club Augsburg".

Ist es Absicht, dass das "Augsburg" etwas nach oben absteht?

**Comment by timjb** [comment]
@iblech Nein, nur Schlampigkeit. Ist jetzt ausgebessert.

**Comment by sternenseemann** [comment]
Mir gefällt die erste Version mit Hintergrund bei Weitem am Besten. Für Schriftarten lohnt es sich ohnehin nach freien zu suchen, dann kann ich diese auch in der Website verwenden.

Das Abschneiden des Haskell-Logos schmeckt mir nicht so ganz, auch die Anlehnung an das OLA-Logo sieht meiner Meinung nach nicht so schön aus, ist aber als Variante sinnvoll, wenn man mal™ nicht so viel Platz hat.

**Comment by timjb** [comment]
Ich finde das Farbschema von haskell.org auch sehr schön. Hier ist obiger Vorschlag in diesem Farben: 

![currying-club-kapital-haskellorg](https://cloud.githubusercontent.com/assets/124073/6736421/fbcd69a4-ce64-11e4-8994-3d3fb74aedc3.png)

(man beachte den dezenten Farbverlauf!)

Das sieht jetzt mehr danach aus, als ob das "r" das ">" überdeckt, nicht abschneidet.

Ich hab das "AUGS\nBURG" so gelassen, weil mir das recht gut gefällt.

**Comment by timjb** [comment]
Mit Typ:

![currying-club-kapital-haskellorg-typ](https://cloud.githubusercontent.com/assets/124073/6736883/05d46224-ce68-11e4-9279-789e62b1e3ff.png)

**Comment by timjb** [comment]
Zweizeiler:

![curry-club-zweizeiler](https://cloud.githubusercontent.com/assets/124073/6737100/b4c5afda-ce69-11e4-8a4a-0ab6001cab9d.png)

**Comment by timjb** [comment]
In der Typsignatur könnte man auch das `b` durch in `u` und das `c` durch ein `x` ersetzen.

**Comment by sternenseemann** [comment]
Das gefällt mir _sehr_ gut.

Wie sieht's mit der Schrift aus?

Mit Openlab-Style Augsburg bin ich okay.

**Comment by iblech** [comment]
Geil! Mit Typsignatur!

**Comment by iblech** [comment]
Auch das große sieht sehr schön aus!

**Comment by timjb** [comment]
@lukasepple Welches Logo gefällt dir? Die Schrift ist die freie Ubuntu-Schriftart.

**Comment by maxhbr** [comment]
Sieht sehr gut aus!

Ich bin auch für Typsignatur, Augsburg geschrieben wie im OpenLab-Logo und für hellen Hintergrund (mit dunkler Alternativversion).

**Comment by iblech** [comment]
Nur eine Trivialbemerkung: Bei "AUGS\nBURG" ist das "BURG" nicht ganz präzise an dem "AUGS" ausgerichtet. Muss natürlich nicht jetzt verbessert werden.

**Comment by fthomas** [comment]
Der Zweizeiler im haskell.org-Stil macht echt was her! :+1: @timjb

**Comment by iblech** [comment]
Für billig gedruckte Aushänge (Standard-Laserdrucker) ist eine (zusätzliche) Version mit weißem Hintergrund sicherlich nützlich (und Hauptfarbe das schöne rot von oben oder das Hintergrund-lila aus den aktuellen Entwürfen mit farbigem Hintergrund). Auf der Webseite haben wir natürlich keine solchen Einschränkungen zu beachten.

Ich glaube, wir können sehr froh mit den jetzigen Entwürfen sein!

**Comment by timjb** [comment]
So, noch ein paar Detailänderungen:
- Unicode-Pfeile
- Hellere Codesignatur
- Ausrichtung von "AUGS\nBURG" verbessert
- Dünnere Schrift für "AUGS\nBURG"
- Änderung der Typvariablen: `a,b,c` -> `a,u,x`

![curry-club-kapital-haskellorg-typ](https://cloud.githubusercontent.com/assets/124073/6739414/bd839948-ce78-11e4-8249-0e9c8f81c418.png)

**Comment by timjb** [comment]
Eine helle Version ist eine gute Idee! Und schaut auch gut aus:

![curry-club-kapital-final1-hell](https://cloud.githubusercontent.com/assets/124073/6739755/3aba2b96-ce7b-11e4-81fa-d66cf4c8af73.png)

**Comment by sternenseemann** [comment]
@timjb Super, du bist toll!

Kannst du noch mal die Details runterschreiben? Also Farbe, Schrift…

Und die Dateien zentral sammeln, dann nehme ich die in das repo auf. (Oder gleich in /images pushen)

**Comment by timjb** [comment]
@lukasepple Du brauchst nur den [Ubuntu-Font](http://font.ubuntu.com/) installiert haben. Ich schicke dir gleich die SVG-Datei (für Inkscape) zu. Du kannst die dann am Besten gleich ins Website-Repo committen (ich mach das mal nicht selber, denn ich vermute, dass du lokale Änderungen hast).

**Comment by timjb** [comment]
Die Datei `images/curry-club-augsburg-logo.svg` enthält jetzt die dunkle und die helle Version des Logos und auch eine quadratische für das Github-Benutzerbild. Mit Inkscape kann man daraus PNG-Dateien exportieren für die Webseite. Oder aber man verwendet eine SVG-Datei, in der nur das Logo zu sehen ist, für die Webseite. Wenn man das macht, dann sollte man aber vorher die Schriftzüge in Pfade umwandeln, damit der Benutzer nicht den Ubuntu-Font installiert haben muss, um das Logo korrekt dargestellt zu bekommen.
