### ISSUE TITLE
Eintrag im OpenLab-Kalender

### ISSUE THREAD

**Issue by iblech** [curry-club-aux/curry-club-augsburg.de#20]
Jemand mit $Berechtigung kann uns im Veranstaltungskalender des OpenLab eintragen: https://openlab-augsburg.de/veranstaltungen/

**Comment by timjb** [comment]
Außerdem sollten wir für einen Eintrag in https://wiki.haskell.org/User_groups sorgen.

**Comment by iblech** [comment]
HaskellWiki übernehme ich.

**Comment by timjb** [comment]
@iblech Wenn du schon einen Account hast.

Ich habe nämlich gerade eine Mail an den Account-Gatekeeper geschrieben.

**Comment by iblech** [comment]
Hab ich eben auch. :-) Schon etwas seltsam, dass man nicht einfach selbst einen Account anlegen kann!

**Comment by timjb** [comment]
So, wir stehen jetzt auch im Haskell-Wiki.

**Comment by sternenseemann** [comment]
Für den OLA-Events-Eintrag bräuchten wir einen kurzen allgemeinen Text.

Nehmen wir dazu folgendes?

> Das Treffen für Haskellistas, Lambdroiden und andere funktionale, kohlenstoffbasierte Lebensformen in Augsburg!
> 
> Der Curry Club soll Treffpunkt sein, um Konzepte und Ansätze, Praktisches und Abstraktes, Purität und Effekte, Faulheit und Striktheit, Monaden und Monoide und sonst auch wirklich alles passende zu diskutieren.

**Comment by iblech** [comment]
On Tue, Apr 21, 2015 at 12:05:41PM -0700, Lukas Epple wrote:

> Nehmen wir dazu folgendes?

Finde ich gut!

**Comment by sternenseemann** [comment]
Alles schon erledigt, das Issue zu schließen wurde wohl vergessen.
