### ISSUE TITLE
Treffensankündigungen über die Blog-Funktion von Hakyll machen

### ISSUE THREAD

**Issue by sternenseemann** [curry-club-aux/curry-club-augsburg.de#21]
- Bei Treffensankündigungen und derem Programm handelt es sich um wechselnde Inhalte
- sie sind begrenzt gültig
- man möchte Interessierte über Änderungen informiert halten

Es zeigt sich also, dass man eigentlich das nicht als Textbaustein auf der Startseite haben möchte, sondern unter „Neuigkeiten“. Dann kann man diese Punkte recht elegant lösen. Für mehr Informationen, kann man auf der Startseite natürlich mehr anzeigen und ein Archiv erstellen lassen.

**Comment by timjb** [comment]
Es ist sicherlich sinnvoll, das Programm mit der Blogfunktion umzusetzen (damit Feed-Abonennten informiert werden). Ich finde, dass das Programm des nächsten Treffens aber schon einen besonderen Platz auf der Webseite verdient hat. Bestimmt lässt sich das auch irgendwie mit Hakyll umsetzen.

Schick wäre auch eine Hakyll-generierte Seite, die nur das Programm vom nächsten Treffen und ein wenig Info zum Curry-Club enthält, die aber ein spezielles Print-Stylesheet mitbringt. Diese Seite kann man dann ausdrucken und aushängen, z.B. an der Uni oder FH.

**Comment by Profpatsch** [comment]
Warum nicht einen Blog-Eintrag schreiben (dabei gleich Markdown aktivieren) und automatisch den neuesten immer als Abschnitt auf der Hauptseite einbinden?

Dabei kann dann auch gleich z.B. auf Blaze umgestiegen werden.
