### ISSUE TITLE
Blogeintrag zum ersten Treffen

### ISSUE THREAD

**Issue by Profpatsch** [curry-club-aux/curry-club-augsburg.de#22]
Schreib ich.

**Comment by iblech** [comment]
Der Eintrag fürs OpenLab ist doch schon super, oder? Wer kann den veröffentlichen? https://ola.pads.ccc.de/curry-club-01?

**Comment by iblech** [comment]
Ah, hast du schon gemacht. Super :-). Und danke, dass du dich assigned hast!

**Comment by Profpatsch** [comment]
Ich bin ein bisschen abgerutscht und habe jetzt deinen Vortrag zusammengefasst. :P

Bin aber dabei.

**Comment by iblech** [comment]
"... und eins führte zum anderen und plötzlich habe ich [Kan-Erweiterungen](http://comonad.com/reader/2008/kan-extensions/) studiert." :-)

PS: Ist [dieses Mem](https://i.imgflip.com/kry6i.jpg) das bisher kategorientheorisch-nerdigste des Internets?

**Comment by Profpatsch** [comment]
Das kann gut sein. :)

_bahnhof, bahnhof, bahnhof_

**Comment by Profpatsch** [comment]
Bin noch dran, ist was dazwischengekommen. Versuche, es heute fertigzubekommen.
