### ISSUE TITLE
Routen verbessern

### ISSUE THREAD

**Issue by Profpatsch** [curry-club-aux/curry-club-augsburg.de#23]
Momentan sind die Routen der Blogeinträge noch relativ simpel und wenig semantisch, z.B.:

```
http://curry-club-augsburg.de/posts/2015-03-17-hallo-welt.html
```

Ich würde vorschlagen, sie folgendermaßen abzuändern:

```
/posts
  Eine Liste aller Posts
/posts/<Jahr>
  Eine Liste aller Posts eines Jahre
/posts/<Jahr>/<Name>
  Der Post <Name> im Jahr <Jahr>
/posts/<Datum>-<Name>
  Der Post mit dem Dateinamen <Datum>-<Name> ohne Endung
```

1 und 2 müssen generiert werden und linken auf Links vom Typ 4, 3 leitet nur auf 4 um.

Da wir eine statische Seite machen, bin ich mir nicht sicher, ob das `a)` mit dem Content-Type so hinhaut (ohne die Endung) und `b)` wie man die Umleitungen baut (http-redirect?).

**Comment by larsrh** [comment]
Denke, das kann geschlossen werden. Wir nutzen die derzeitigen URLs nun schon seit einer gewissen Zeit und das jetzt noch umzubiegen ist glaube ich wenig sinnvoll.

**Comment by Profpatsch** [comment]
Jo, ist vllt. von Kosten-Nutzen nicht so sinnvoll.
