### ISSUE TITLE
https einrichten

### ISSUE THREAD

**Issue by Profpatsch** [curry-club-aux/curry-club-augsburg.de#24]
Mit Weiterleitung von http.

**Comment by iblech** [comment]
+1

**Comment by timjb** [comment]
Die Seite ist schon mit HTTPS erreichbar, allerdings nur unter der unhandlichen URL

https://curry-club-aux.github.io/curry-club-augsburg.de/

Ich verstehe allerdings nicht so ganz, was der Nutzen von HTTPS wäre bei unserer Seite.

**Comment by iblech** [comment]
Kein besonderer Nutzen, aber HTTPS ist ja allgemein zu bevorzugen.

**Comment by timjb** [comment]
Ohne Frage! Wenn es eine einfache und wartungsarme Möglichkeit gibt, SSL zu aktivieren, bin ich sofort dafür! (Eine Option wäre vielleicht [CloudFlare](https://www.cloudflare.com/) zu verwenden, eine andere zu warten, bis Github Pages endlich auch HTTPS für custom domains unterstützt.) Ich habe aber keine Lust, Zeit damit zu verbringen, einen eigenen Webserver für die Seite aufzusetzen, dem SSL beizubringen oder Geld für ein Zertifikat auszugeben, um letztendlich nur ein paar Coolness-Punkte für unseren Club zu sammeln.

**Comment by iblech** [comment]
Ja, Aufwand soll es keiner sein! Krass, dass GitHub Pages nicht SSL unterstützt, oder?

**Comment by sternenseemann** [comment]
Sehr wohl! Das Zertifikat ist aber nur für `*.github.io` ausgestellt, folglich wäre das Zertifikat von jedem Browser als ungültig bewert, wenn plötzlich die Domain `curry-club-augsburg.de` ist. Darum schaltet Github SSL scheinbar für custom domains ab. Für jede custom Domain ein Zertifikat erstellen zu lassen, ist für Github natürlich zu teuer, das zeigt aber auch wieder nur, wie kaputt das System ist.

**Comment by sternenseemann** [comment]
Ich schließe das mal.

**Comment by Profpatsch** [comment]
Why? Das ist immer noch ein Issue, das man beheben sollte.

**Comment by sternenseemann** [comment]
Naja, wie dargelegt, wird es Github nicht fixen. Die einzig räsonable Lösung wäre, einen eigenen Server zu betreiben und ein SSL Zertifikat zu kaufen, was aber noch mehr kosten als nur die Domain, die @timjb freundlicherweise bezahlt generieren.

**Comment by larsrh** [comment]
Ich würde meinen Server anbieten; kann gerne (eingeschränkte) SSH-Zugänge einrichten. Ggf. können da auch cronjobs laufen. Zertifikat wäre auch kein Problem.

**Comment by larsrh** [comment]
SSL-Zertifikate gibts übrigens auch für lau, z.B. von StartCom.

**Comment by Profpatsch** [comment]
Jau, was anderes als StartCom würde ich auch gar nicht verwenden, zumindest bis Let’s Encrypt nicht soweit ist.

Wir brauchen vermutlich gar keinen Server dafür, das ist ja statisch das ganze, es müsste direkt von der Hydra aus machbar sein.

**Comment by sternenseemann** [comment]
Es hat sich aber gezeigt, dass ein eigener Server für weitere Anwendungen, (files abladen, Dinge mirroren, eigene Applikation irgendwannmal) schon sinnvoll wäre. Hydra zu nutzen ist schon wieder so ein eigentlich ganz cooler Hack, aber auf lange Sicht umständlich und unflexibel.

**Comment by photm5** [comment]
Scheinbar steht das mit dem wontfix noch nicht so ganz fest, daher entferne ich das label mal...

**Comment by larsrh** [comment]
Das Angebot mit dem Server steht auch noch.

**Comment by sternenseemann** [comment]
Sieht so aus als würden wir das nur ändern, wenn wir mal $Dinge laufen lassen wollen, die dynamisch sind.

Close?

**Comment by Profpatsch** [comment]
Von mir aus.

**Comment by sternenseemann** [comment]
Fixen wir halt dann mal™, wenn wir eh einen Server™ brauchen™. Dann aber mit letsencrypt!

**Comment by timjb** [comment]
Ich habe kürzlich folgende E-Mail bekommen. (Ihr vermutlich auch?)

> Hey Tim Baumann!
> 
> I am @nubela on Github and I found your project (curry-club-aux/curry-club-augsburg.de) on Github. There is a small chance you might have heard of some of my projects such as Javelin Browser or Gom VPN.
> 
> Anyways, I found that Github Page at curry-club-aux/curry-club-augsburg.de has a custom domain, and I was wondering if I can help you get it to HTTPS with a LetsEncrypt cert? (for free, of course!)
> 
> I work at Kloudsec (a free and minimal CDN for programmers) and I just built this tool [1] to provision LetsEncrypt certs for github pages. 
> 
> Will you like to try it? (and help me test it?) ;)
> 
> Steven.
> 
> [1] https://kloudsec.com/github-pages

Wollen wir das mal ausprobieren?

**Comment by sternenseemann** [comment]
Ich auch. Schon fishy.

Mir misshagt halt der Gedanke, einen CDN-Cloud-Buzzword™ Service zu benutzen und **die** sich um **unser** https kümmern.

**Comment by iblech** [comment]
Ja, im Sinne von https ist es sicher nicht, dass sich jemand anderes um unsere Zertifikate kuemmert. Auf der positiven Seite fand ich die Mail durchaus nett und hoeflich formuliert und auch die Webseite macht mir nicht einen zu schlechten Eindruck. (War heute durch Zufall auf der Seite von Akismet, einem wohl ganz guten Anti-Spam-Service. Aber der PHP-Code in ihrer Doku hat keinen guten Eindruck gemacht.)

**Comment by diekmann** [comment]
Wir sind wohl nicht die einzigen, die genau diese Mail bekommen haben. Keine Ahnung ob da nur jmd nett ist und seine Firma pushen will oder ob das scam ist.
