### ISSUE TITLE
Syntax-Hilighting aktivieren

### ISSUE THREAD

**Issue by Profpatsch** [curry-club-aux/curry-club-augsburg.de#27]
Pandoc sollte das können.

**Comment by Profpatsch** [comment]
@timjb Was hältst du davon, den ganzen Text #c5c8c6 (Die Farbe von Misc-Codesyntax) zu machen? Eventuell auch das Logo?

Momentan finde ich der #fff Text sticht sich mit dem lila Hintergrund.

**Comment by timjb** [comment]
Du hast recht, dass der Kontrast etwas zu krass ist. Den Grauton `#c5c8c6` finde ich aber auch nicht schön. Ich habe jetzt ein Hellgelb genommen, was imho sehr gut zum lila Hintergrund passt.

Das Logo habe ich noch nicht angepasst, da ich aus Festplattenplatznot Inkscape bereits wieder deinstalliert habe.

**Comment by Profpatsch** [comment]
Ja, gelb ist besser, da kompatibel mit lila. :)
