### ISSUE TITLE
Domain?

### ISSUE THREAD

**Issue by sternenseemann** [curry-club-aux/curry-club-augsburg.de#3]
Will man das? Wie bezahlen wir das? Wo holen wir die?

**Comment by timjb** [comment]
Ja; das würde ich übernehmen; bei Namecheap (da hab ich auch meine eigene Domain)

Vierte Frage: Welche Domain überhaupt?

**Comment by sternenseemann** [comment]
Da hätten wir in #1 wohl mal ne Entscheidung von Nöten? :D

**Comment by iblech** [comment]
curry-club.de ist schon vergeben. augsburger-curry-club.de? chaos-curry-club.de? ccccc.de?

**Comment by sternenseemann** [comment]
curry.de? cc.de? curry-club-aux.de?

**Comment by iblech** [comment]
Die ersten beiden (curry.de und cc.de) sind leider schon vergeben.

Bisher finde ich curry-club-aux.de am besten (gefolgt von chaos-curry-club.de).

Übrigens ist cartesian.de noch frei. Ist auf einer absoluten Skala sicherlich sehr cool, enthält aber nicht unsere Namensbestandteile.

**Comment by timjb** [comment]
Ich bin für curry-club-aux.de. Auch gut, wenn auch etwas zu lang, finde ich curry-club-augsburg.de.

**Comment by timjb** [comment]
Inzwischen finde ich curry-club-augsburg.de besser als curry-club-aux.de. Die Länge von URLs ist heutzutage eh ziemlich egal. Wenn man in Chrome/Firefox die ersten zwei, drei Buchstaben eingibt, schlägt Chrome/Firefox einem eh den Rest vor.

Die Domain `curry-club-aux.de` wurde bisher aber schon zweimal vorgeschlagen. Wenn niemand bis dahin Einwände erhebt, werde ich diese Domain heute um 21:00 Uhr registrieren.

**Comment by iblech** [comment]
@rueger hat sich in #1 für curry-club-augsburg.de ausgesprochen. Ich selbst bin mir mittlerweile nicht mehr sicher. Carina meint, curry-club-aux.de würde sie weniger an Pommesbuden erinnern als curry-club-augsburg.de.

Ich stimme zu, dass die URL-Länge ziemlich irrelevant ist.

Mal sehen, was $andere bis 21:00 Uhr sagen!

**Comment by timjb** [comment]
# Abstimmungskommentar

(bitte editieren, wenn ihr die Berechtigung dazu habt; ansonsten unten einen Kommentar mit Bitte auf Eintragung hinterlassen):
- `curry-club-aux.de`: Carina, @maximilianhuber
- `curry-club-augsburg.de`: @timjb, @rueger, @fthomas, Peter, @lukasepple

**Comment by rueger** [comment]
schmeckt currying-club-augsburg.de weniger nach pommes? möchte aber #1 nicht nochmal öffnen...

**Comment by timjb** [comment]
![currying-club](https://cloud.githubusercontent.com/assets/124073/6730215/a742d178-ce3a-11e4-85b0-c089a1b3ea54.png)

**Comment by maxhbr** [comment]
ich wäre auch für Currying-Club{,-Augsburg}

**Comment by timjb** [comment]
Mir gefällt Curry Club besser. Das ist prägnanter, lässt sich besser aussprechen und das Logo sieht besser aus, wenn das "=" mit dem Wort abschließt.

**Comment by sternenseemann** [comment]
Curry Club Augsburg soll bleiben, finde ich

**Comment by sternenseemann** [comment]
Ich denke, dann wird's curry-club-augsburg.de

**Comment by maxhbr** [comment]
ok, dann freunde ich mich auch damit an

**Comment by timjb** [comment]
So, das Voting ist vorbei, mir gehört jetzt `curry-club-augsburg.de` (die Siegerdomain mit 5:2 Stimmen).

**Comment by iblech** [comment]
Prima!

**Comment by timjb** [comment]
So, dieses Repo heißt ab jetzt `curry-club-aux/curry-club-augsburg.de`.

**Comment by timjb** [comment]
:bell: Die Webseite ist jetzt [online](http://curry-club-augsburg.de)! :bell:

**Comment by sternenseemann** [comment]
wooo

**Comment by timjb** [comment]
Ich habe eine Mail-Adresse eingerichtet: post@curry-club-augsburg.de. Die Nachrichten werden momentan an meine private Adresse weitergeleitet.

**Comment by sternenseemann** [comment]
Habe ich vermerkt, Travis is compiling again…
