### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by larsrh** [curry-club-aux/curry-club-augsburg.de#39]
... gibt es derzeit anscheinend nicht. Wir sollten mal so etwas wie CC-BY festlegen.

**Comment by larsrh** [comment]
Für eine Lizenz müssten folgende Personen zustimmen:
- [x] @timjb 
- [x] @iblech 
- [x] @lukasepple 
- [x] @Profpatsch 
- [x] @maximilianhuber 
- [x] @aszlig 
- [x] @shak-mar 
- [x] @MatthiasHu 
- [x] @larsrh

**Comment by iblech** [comment]
Jup. Kennt jemand einen guten Blog-Post, der CC-BY und CC-(BY)-SA
vergleicht?

**Comment by sternenseemann** [comment]
Naja, SA, enforced halt, dass man alles unter derselben Lizenz weitergeben muss.

**Comment by sternenseemann** [comment]
@iblech [Hier](http://creativecommons.org/choose/)

**Comment by iblech** [comment]
Okay, klar. Aber welche Lizenz ist Die Richtige (TM) für Texte, wenn man
ansonsten ein Verfechter freier Software ist? Da gibt es doch sicher
Diskussionen drüber.

**Comment by Profpatsch** [comment]
Meine Stimme ist CC-BY-SA für Texte, GPLv3 or later für Code.

**Comment by timjb** [comment]
Ich bin für CC-BY für Texte, MIT für Code.

**Comment by maxhbr** [comment]
+1 für: **CC-BY** für Texte, **MIT** für Code.

**Comment by sternenseemann** [comment]
Jetzt kommt der Open-Source vs. Free-Software war.

GPLv3 für Code, CC-BY oder CC-BY-SA für Text.

**Comment by larsrh** [comment]
Sowohl GPL als auch MIT sind sowohl free als auch open source.

Generell bin ich für MIT (oder eine andere permissive Lizenz), wäre aber auch mit GPL einverstanden.

**Comment by sternenseemann** [comment]
Naja, der FSF-Terminologie sind nur die GPL-Lizenzen Free as in Freedom, weil sie die Freiheit der Software erzwingen. Die MIT-Lizenz dagegen stützt eher die Freiheit des Individuums.

**Comment by larsrh** [comment]
Das ist faktisch falsch. MIT erfüllt auch die 4 von der FSF vorgegebenen Freiheiten. Copyleft ist keine Bedingung.

**Comment by sternenseemann** [comment]
Tatsächlich? Wusste ich nicht.

**Comment by larsrh** [comment]
Siehe auch http://www.gnu.org/licenses/license-list.html#X11License

**Comment by Profpatsch** [comment]
Ich denke, das lässt sich am einfachsten durch Abstimmung lösen. Wenn alle ihre Meinung gesagt haben, nehmen wir einfach die Lösung mit den meisten Stimmen.

**Comment by iblech** [comment]
Bin auf jeden Fall mit CC-BY, CC-BY-SA und CC-SA happy. Da ich mit aber zuletzt vor Aufkommen der CC-Lizenzen mit Lizenzen beschäftigt habe, würde mich interessieren, was deine, @Profpatsch, Argumente für SA sind und was eure, @larsrh, @timjb, @maximilianhuber, für Verzicht auf SA sind.

**Comment by Profpatsch** [comment]
Ich bin der Meinung, dass die Welt ein generell besserer Ort wird, wenn Software frei ist. Wenn ich mit meinen Lizenzen erreichen kann, dass andere ihre Software auch frei machen, dann tue ich das gerne. Wenn andere meine Software nicht verwenden wollen, weil sie keine freien Lizenzen mögen, dann ist das ok.

Wenn man von freien Lizenzen überzeugt ist, sollte man imho auch dafür kämpfen. Das schränkt natürlich die Freiheit des anderen ein, meinen Code beliebig zu nutzen. Aber in dem Fall fangen die Freiheiten der anderen an, wo meine aufhören. :)

SA ist die gleiche Argumentation, aber halt für kreative Arbeiten, die nicht aus ausführbarem Code bestehen.

**Comment by larsrh** [comment]
Wir können Lizenzen als oberen Halbverband modellieren, wobei die "join"-Operation aus einer Menge an Lizenzen die Lizenz liefert, die zu allen kompatibel ist (bzw. die spezielle Unlizenz, die immer kompatibel ist, aber keinerlei Rechte beinhaltet). Glücklicherweise ist join(MIT, GPL) = GPL, so dass alle, die mit MIT einverstanden sind, auch automatisch mit GPL einverstanden sind. Gleiches gilt für CC-BY und -SA. Insofern würde ich jetzt noch die restlichen Beitragenden um Bestätigung bitten. :smile:

**Comment by sternenseemann** [comment]
Das ist großartig.

**Comment by larsrh** [comment]
Wenn man noch die Alllizenz (alle Rechte) hinzunimmt, kommt vermutlich auch ein ordentlicher Verband raus.

**Comment by timjb** [comment]
Ich bin der Meinung, dass die Welt ein generell besserer Ort wird, wenn mehr Programmierer und auch Unternehmen Haskell verwenden. Wenn ich mit meinem Software und Tutorials dazu beitragen kann, dieses Ziel zu erreichen, dann tue ich das gerne. Es wäre schade, wenn andere aus Lizenzgründen nicht von meiner Software oder Tutorials Gebrauch machen wollen, denn dies schadet auch der Verbreitung von Haskell. Es wäre beispielsweise für mich völlig in Ordnung, wenn eine Software-Firma unsere Übungsaufgaben für eine interne Schulung verwendet, oder ein Buch-Autor sie veröffentlicht (unter Namensnennung).

Falls die Mehrheit anderer Meinung ist, dann schließe ich mich dem an.

**Comment by iblech** [comment]
Ein ähnliches Argument steht auf http://www.gnu.org/licenses/license-recommendations.html (Abschnitt Libraries).

**Comment by MatthiasHu** [comment]
Da ich oben bei "müssten [...] zustimmen" genannt bin: Für mich wäre jede der genannten Lizenzen akzeptabel.

**Comment by photm5** [comment]
Für mich auch.

**Comment by larsrh** [comment]
@lukasepple, wie sieht es bei dir aus?

**Comment by sternenseemann** [comment]
Ich würde auch allen genannten optionen zustimmen.

**Comment by Profpatsch** [comment]
Dann ist es CC-BY & MIT.

**Comment by sternenseemann** [comment]
Yess.

**Comment by larsrh** [comment]
Habe mich assigned. Pull request wird schätzungsweise morgen kommen.

**Comment by sternenseemann** [comment]
Nice.
