### ISSUE TITLE
Inhalte!

### ISSUE THREAD

**Issue by sternenseemann** [curry-club-aux/curry-club-augsburg.de#4]
Schreibt mal ein bisschen was, ich muss noch einiges erledigen und mit LaTeX kämmpfen!

**Comment by timjb** [comment]
@lukasepple Wenn das Zeug, das du erledigen musst nicht ganz so dringend ist, dann ist das hier eigentlich eine gute Möglichkeit für [produktive Prokrastination](http://www.structuredprocrastination.com/) ;-)

Ich muss auch noch dringend bis Sonntag einen Vortrag vorbereiten. Ich selbst habe gestern und heute schon genügend prokrastiniert. Die nächste Woche werde ich nicht da sein und keine Zeit haben.

Mal ne andere Frage: Brauchen wir überhaupt eine Mailingliste? Github Issues tuts doch eigentlich auch.

**Comment by sternenseemann** [comment]
Naja, für generelle Diskussionen und Planung ist es besser, da passt das hier nicht so. Und unterschätze nicht, wie viele keinen GitHub Account haben.

**Comment by sternenseemann** [comment]
Und ja, es ist dringend :(

**Comment by iblech** [comment]
Am Wochenende bin ich in Worms und werde voraussichtlich kein Internet haben. Danach kümmere ich mich aber gerne um Inhalte; aus meiner Sicht ist zu tun:
- Werbe-Text zu unserem Haskell-Anfänger-Workshop
- Vortragsplanung (aber inwieweit ist hier das Wiki besser?)
- Sammlung von etwas Materialien (wobei man aufpassen muss, nicht einfach haskell.org zu wiederholen)

Sobald dann die Treffen angelaufen sind, kommen natürlich Vortragsfolien dazu. Vielleicht versuche ich mich auch an CSS-Liebe. Wobei ich zugeben muss, dass ich CSS vor 15 Jahren gelernt habe und nicht auf dem aktuellen Stand bin.

**Comment by sternenseemann** [comment]
CSS Liebe übernehme ich gerne, da finde ich hoffentlich noch Zeit

**Comment by sternenseemann** [comment]
Ich habe da mal was gemacht. Das passt so, wir müssten jetzt noch Zeit usw. entscheiden

**Comment by sternenseemann** [comment]
Inhaltsaggregation läuft ja inzwischen.
