### ISSUE TITLE
Artikel über cabal?

### ISSUE THREAD

**Issue by sternenseemann** [curry-club-aux/curry-club-augsburg.de#41]
Auch interessant für die Workshopteilnehmer, für andere aber weniger?!

**Comment by Profpatsch** [comment]
y not

**Comment by iblech** [comment]
Auch hier +1. Das kann man ja recht kurz halten, oder? Und man könnte
sich überlegen, nur stack vorzustellen. (Ich selbst habe es, _schäm_,
noch nie probiert -- sitze auf einem alten Ubuntu fest.)

Für Spaß kann man auch die Abhängigkeitsliste irgendeines Web-Frameworks
zeigen und die witzigen Module (yoneda, kan-extensions, ...) markieren. :-)

**Comment by sternenseemann** [comment]
Ja, man sollte noch auf nix und stack eingehen, wobei stack natürlich deutlich niederschwelliger ist.

**Comment by Profpatsch** [comment]
@lukasepple willst du das noch schreiben?

**Comment by sternenseemann** [comment]
Achja.

**Comment by Profpatsch** [comment]
Ja? Nein? Vielleicht?

**Comment by sternenseemann** [comment]
Wenn ich mal Zeit™ habe? _duck_
