### ISSUE TITLE
Linking site.hs dauert ewig

### ISSUE THREAD

**Issue by Profpatsch** [curry-club-aux/curry-club-augsburg.de#42]
So 10–20s bei mir.
Gibt es da einen Trick, das das langsamer geht? Wie kann man es profilen?

**Comment by sternenseemann** [comment]
Linken dauert allgemein lange beim GHC. :(

**Comment by Profpatsch** [comment]
Ich denke, weil er das alles statisch reinkopiert. Man kann auch irgendwie dynamisch linken, ich hab aber noch nicht rausbekommen, wie das mit cabal genau geht.

Alternativ kann man auch einen schnelleren Systemlinker einstellen: https://en.wikipedia.org/wiki/Gold_%28linker%29

**Comment by larsrh** [comment]
Das ist leider ein generelles Problem in Haskell was wir lokal nicht lösen können.

**Comment by Profpatsch** [comment]
Link? Grund?

**Comment by sternenseemann** [comment]
Warum reopenest du das denn?
