### ISSUE TITLE
Seitenbaufehler

### ISSUE THREAD

**Issue by sternenseemann** [curry-club-aux/curry-club-augsburg.de#46]
```
[ERROR] Missing field $next-meetup-date$ in context for item index.html
```

Mir ist unerklärlich, woher das kommt.

**Comment by timjb** [comment]
Fehlender Blogpost fürs nächste Treffen?

**Comment by sternenseemann** [comment]
Ah.

**Comment by sternenseemann** [comment]
Mach' ich schnell.

**Comment by Profpatsch** [comment]
lel, sollte man aber trotzdem fixen.

**Comment by sternenseemann** [comment]
Ist doch fixed.

**Comment by Profpatsch** [comment]
Bis nach dem nächsten Treffen meinst du.

**Comment by sternenseemann** [comment]
Muss mal halt wissen™

Wird aber auch nur pro commit neu gebaut…

**Comment by Profpatsch** [comment]
Ist halt extrem kacke und leicht zu fixen.

**Comment by Profpatsch** [comment]
Außerdem hab ich das mit dem letzten Patch verkackt. :)

**Comment by sternenseemann** [comment]
Sie sind assigned :)
