### ISSUE TITLE
Mailingliste neu aufsetzen

### ISSUE THREAD

**Issue by iblech** [curry-club-aux/curry-club-augsburg.de#52]
Durch den Ausfall des OpenLab-Servers, auf dem unsere Mailingliste lief, haben wir leider die Subscriberliste verloren. (Wir haben leichtsinnigerweise kein Backup gemacht.) In Kürze wird die Mailingliste wieder funktionieren, aber es werden sich alle Interessierten neu anmelden müssen.

Dieses Issue soll als Erinnerung an alle Beteiligten dienen und den Verlauf des neuen Aufsetzens dokumentieren.

**Comment by Profpatsch** [comment]
Die 3d-Druckerleute haben alle Absender auf ihrer Liste wieder eingetragen. Da bleiben die Lurker natürlich auf der Strecke.

**Comment by iblech** [comment]
Jup die Absenderinnen haben wir auch schon extrahiert. (Obligatorischer xkcd-Verweis.)

**Comment by timjb** [comment]
Ich habe die IP-Adresse im DNS angepasst. Allerdings habe ich noch nicht verifizieren können, dass Mails an die Liste an die Subscriber verteilt werden. (Auf meine Testmail habe ich keine Antwort bekommen.)

**Comment by uwap** [comment]
Ich habe tatsächlich keine Testmail von dir bekommen, falls du meintest,
dass du eine Mail auf die neue CurryClub ML geschickt hast.

**Comment by Profpatsch** [comment]
Ich habe vor einer Stunde auch eine Testmail geschickt, es kam aber nichts an (zumindest bei mir). Und das Archiv ist ja schon wieder 404, weil schlecht aufgesetzt.

**Comment by uwap** [comment]
Deine Aktuelle Testmail kam bei mir aber an. Also die von 1:14.

**Comment by Profpatsch** [comment]
Ja, die ging an `curry-talk@lists.openlab-augsburg.de`, also scheint der DNS Redirect noch nicht so zu funktionieren, wie er sollte.

**Comment by uwap** [comment]
Es gab eine andere Mailadresse für die Curry Club ML? o_O

**Comment by timjb** [comment]
Ich hatte meine Testmail an `curry-talk@lists.curry-club-augsburg.de` gesendet.

Ich habe darauf jetzt eine Fehlerbenachrichtungsmail bekommen:

```
[...]

                   The mail system

<curry-talk@lists.curry-club-augsburg.de>: host
    lists.curry-club-augsburg.de[5.135.183.38] said: 454 4.7.1
    <curry-talk@lists.curry-club-augsburg.de>: Relay access denied (in reply to
    RCPT TO command)
```

**Comment by timjb** [comment]
Ich habs gerade noch einmal probiert mit einer Probemail, klappt immer noch nicht. Kann mal bitte jemand schauen, ob ich was falsch eingerichtet habe?

```
$ host -a lists.curry-club-augsburg.de
Trying "lists.curry-club-augsburg.de"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23940
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;lists.curry-club-augsburg.de.  IN  ANY

;; ANSWER SECTION:
lists.curry-club-augsburg.de. 1800 IN   MX  50 mail.curry-club-augsburg.de.

Received 67 bytes from fd00::3631:c4ff:fe81:6dd8#53 in 40 ms

$ host -a mail.curry-club-augsburg.de
Trying "mail.curry-club-augsburg.de"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43239
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mail.curry-club-augsburg.de.   IN  ANY

;; ANSWER SECTION:
mail.curry-club-augsburg.de. 1800 IN    A   5.135.183.38

Received 61 bytes from fd00::3631:c4ff:fe81:6dd8#53 in 30 ms
```

**Comment by uwap** [comment]
Ich vermute eher, dass der Postfix falsch konfiguriert ist. Ist die
Postfix Config auch irgendwo auf Github?

**Comment by Profpatsch** [comment]
> Relay access denied (in reply to
>     RCPT TO command)

Das sieht aus wie ein falsch konfigurierter Postfix, ja.
Kann jemand dem @waaaaargh eine Mail schreiben?

**Comment by Profpatsch** [comment]
Hm, jetzt geht aber http://lists.curry-club-augsburg.de/ auch nicht mehr.

**Comment by timjb** [comment]
@Profpatsch Das habe ich kaputt gemacht, als ich heute an dem DNS rumgespielt habe. Ist jetzt korrigiert.

**Comment by Profpatsch** [comment]
Ah, dann hat sich das nur noch nicht bis hier durchpropagiert.

**Comment by timjb** [comment]
Irgendwas ist passiert und jetzt sind alle meine Testmails angekommen! (Sorry für den Spam.)

Ich kann leider nicht die Liste der Mailadressen neu eintragen, da ich das List-Moderator-Passwort nicht kenne.

**Comment by sternenseemann** [comment]
Funktioniert jetzt alles, oder?

**Comment by iblech** [comment]
Können wir noch herausfinden, wer Administratorrechte hat, damit wir alle ehemaligen Posterinnen wieder hinzufügen können?

**Comment by Profpatsch** [comment]
@timjb ist Admin, ich bin Superadmin (alle Listen)

**Comment by GraffL** [comment]
Kann es sein, dass man sich für die Mailingliste noch nicht wieder neu anmelden kann? 
(oder stelle ich mich nur dumm an?)

**Comment by sternenseemann** [comment]
<http://lists.curry-club-augsburg.de>

**Comment by sternenseemann** [comment]
Einfach hier? https://lists.openlab-augsburg.de/listinfo/curry-talk

**Comment by GraffL** [comment]
Jup, genau da. 
Hab's grade sicherheitshalber nochmal probiert - scheint aber immer noch nicht zu funktionieren.

**Comment by Profpatsch** [comment]
Doch doch, sind schon einige Menschen angemelde. Was geht denn nicht?

**Comment by GraffL** [comment]
Interessant - dann sollte der Fehler wohl eher auf meiner Seite liegen...

Ich habe jetzt mal versucht mich mit einer anderen Mail-Adresse anzumelden und mit der hat es jetzt tatsächlich funktioniert. Faszinierend... :O

**Comment by iblech** [comment]
@Profpatsch, ich schick dir eine Liste von allen Leuten, die was auf der alten Liste geschrieben haben. Kannst du sie dann vielleicht in die neue Liste eintragen? (Ich möchte ungern Leute, die gerade viel um die Ohren haben und unseren Mailfail nicht mitbekommen haben, ausschließen.) Dann können wir dieses Issue schließen. :-)

**Comment by Profpatsch** [comment]
Jau, mach ich dann.

**Comment by MatthiasHu** [comment]
Der Infokasten dazu auf der Hauptseite sollte auch noch aktualisiert werden.

Den zweiten und dritten Absatz löschen und den ersten um einen Link, wo man sich eintragen kann, ergänzen? In der Form sollten wir den Infokasten dann noch ein paar Wochen/Monate stehen lassen, oder?

**Comment by iblech** [comment]
@MatthiasHu: Go for it!

**Comment by MatthiasHu** [comment]
Done.

**Comment by iblech** [comment]
Danke Matthias! @Profpatsch, hast du schon alle Nicht-Lurkerinnen wieder eingetragen? Dann können wir dieses Issue schließen. :-)

**Comment by Profpatsch** [comment]
Ne, noch nicht. Mache ich jetzt.

**Comment by Profpatsch** [comment]
Done.
