### ISSUE TITLE
Travis ist b0rken

### ISSUE THREAD

**Issue by Profpatsch** [curry-club-aux/curry-club-augsburg.de#59]
https://travis-ci.org/curry-club-aux/curry-club-augsburg.de/builds/168141207

Er will stack bauen und das ist kaputt. Was spricht dagegen, dafür cabal zu benutzen?

**Comment by timjb** [comment]
Ich finde `stack` gut, weil Builds durch die Angabe der genauen Versionsnummern der Dependencies besser reproduzierbar sind und dadurch auch zuverlässiger funktioniert als cabal.

Die Fehlermeldung sagt ja, was das Problem ist: Nämlich, dass das Programm `hs2hsc` nicht im Pfad ist. Warum installieren wir darum nicht einfach `hs2hsc` mit `stack` in der `.travis.yml`?

Zu deiner Mail auf der Curry-Club-Liste: Nein, Stackage [lts-6.22](https://www.stackage.org/lts-6.22) ist nicht uralt, sondern vor fünf Tagen released worden. Ich glaube auch nicht, dass ein Update auf `lts-7` den Build fixen wird.

**Comment by Profpatsch** [comment]
> Warum installieren wir darum nicht einfach hs2hsc mit stack in der .travis.yml

Mir eigentlich egal, solange die Seite wieder baut. Ich blicke in der `.travis.yml` nicht durch.
Update: Gerne auch den Commit wieder reverten, das hat alles eh nicht funktioniert.

**Comment by timjb** [comment]
Ich werde jetzt probieren, den Build zu fixen. Bitte keine Force-Pushes jetzt (außer den meinen natürlich)!

**Comment by timjb** [comment]
Der Commit d378d1c5bf4abf7c016437d01cdc93cd5ba6a25f hat den Build gefixt. Problem war wohl, dass irgendeine Änderung, vielleicht an Stack, vielleicht an den [hvr-ghc-Paketen](https://launchpad.net/~hvr/+archive/ubuntu/ghc), dafür gesort hat, dass `hsc2hs` nicht mehr (oder nun außerhalb des `PATH`s) installiert war. Mein Patch sorgt dafür, dass `/opt/ghc/7.10.3/bin` im `PATH` ist. Dort wird dann auch `hsc2hs` gefunden.
