### ISSUE TITLE
Datum/Wochentag nächstes Treffen falsch

### ISSUE THREAD

**Issue by diekmann** [curry-club-aux/curry-club-augsburg.de#67]
Auf der Startseite steht, dass das nächste Treffen am "Donnerstag, den 21.01.2017, 19:00 Uhr MEZ." ist. Der 21.01.207 ist ein Samstag. Was soll ich nun glauben? Was ist noch real, wo verschwimmen die Grenzen zum Cyber?

**Comment by uwap** [comment]
Am 21.01.2017 ist der Haskell Workshop, also ist so gesehen ja ein Curry Club, wenn auch kein Haupttreffen. Daher nicht Donnerstags.

**Comment by timjb** [comment]
Ich habe den Code, der den nächsten Termin berechnet, mit Commit e88a6b0cda5695b70f4bc424d33ab2e1bcc0bfa2 gefixt. Nun werden nur noch reguläre Treffen (repräsentiert durch Posts mit gesetztem Feld `meetup-counter`) berücksichtigt.
