### ISSUE TITLE
HTTPS-Sicherheitswarnung bei Mailinglistenanmeldung

### ISSUE THREAD

**Issue by iblech** [curry-club-aux/curry-club-augsburg.de#69]
Liebe Lambdroiden,

wenn man von unserer Webseite aus versucht, dem Link zur Mailinglistenanmeldung zu folgen, erhält man eine SSL-Warnmeldung: https://lists.curry-club-augsburg.de/listinfo/curry-talk

Sollten wir stattdessen einfach auf lists.openlab-augsburg.de verweisen, oder ist es (möglicherweise aus mailservertechnischen Gründen) schlecht, nur das Symptom zu beheben?

Viele Grüße
Ingo

**Comment by Profpatsch** [comment]
Muss man auf dem OpenLab nginx die Domain (`lists.curry-club-augsburg.de`) noch hinzufügen und ein Zertifikat ausstellen. cc @richi235

**Comment by sternenseemann** [comment]
ein fleißbienchen für @robinkaranu
