### ISSUE TITLE
Logos exportieren

### ISSUE THREAD

**Issue by sternenseemann** [curry-club-aux/curry-club-augsburg.de#8]
Bitte, ich glaube ich baue da unglaublichen Mist mit Inkscape.

**Comment by timjb** [comment]
Bitteschön: `images/logo-{dunkler,heller}-hintergrund.svg`. Das sollten alle Browser unabhängig von den lokal installierten Schriftarten richtig darstellen können. Der Hintergrund selbst ist nicht dabei (damit man den leicht austauschen kann). Das dunkle Lila ist `#2d1630ff`.

**Comment by sternenseemann** [comment]
Danke!
